app.security.allowed-extensions=txt,pdf,doc,docx,csv,json,md

server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
logging.level.com.mrpl.saiw=DEBUG
