import {
  ArrowUpRight,
  Download,
  FileText,
  ShieldCheck,
  X,
} from "lucide-react";

import type { Deliverable } from "../../../types/deliverables";

import DeliverableStatus from "./DeliverableStatus";

type Props = {
  item: Deliverable | null;
  onClose: () => void;
};

export default function DeliverableDetails({
  item,
  onClose,
}: Props) {
  if (!item) {
    return null;
  }

  const deliverable = item;

  function handleDownload() {
    window.alert(
      `Mock download: ${deliverable.name}.${deliverable.type.toLowerCase()}`,
    );
  }

  function handleViewResult() {
    window.location.href = "/ai-studio";
  }

  function handleAudit() {
    window.location.href = `/audit?event=${deliverable.auditId}`;
  }

  return (
    <>
      <div
        className="deliverable-details-overlay"
        onClick={onClose}
      />

      <aside className="deliverable-details">
        <div className="deliverable-details__header">
          <div>
            <span>DELIVERABLE</span>

            <h2>{deliverable.name}</h2>

            <code>{deliverable.id}</code>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="deliverable-details__close"
          >
            <X size={16} />
          </button>
        </div>

        <div className="deliverable-details__status">
          <DeliverableStatus status={deliverable.status} />

          <span>
            {deliverable.type} • {deliverable.version}
          </span>
        </div>

        <div className="deliverable-preview">
          <div className="deliverable-preview__icon">
            <FileText size={28} />
          </div>

          <strong>{deliverable.name}</strong>

          <span>
            {deliverable.type} document • {deliverable.size}
          </span>
        </div>

        <div className="deliverable-details__actions">
          <button
            type="button"
            onClick={handleViewResult}
          >
            <ArrowUpRight size={14} />
            View Result
          </button>

          <button
            type="button"
            onClick={handleDownload}
          >
            <Download size={14} />
            Download
          </button>
        </div>

        <div className="deliverable-details__description">
          <span>DESCRIPTION</span>

          <p>{deliverable.description}</p>
        </div>

        <div className="deliverable-details__fields">
          <div>
            <span>Task Reference</span>
            <strong>{deliverable.taskId}</strong>
            <small>{deliverable.taskName}</small>
          </div>

          <div>
            <span>Evidence</span>
            <strong>{deliverable.evidenceCount}</strong>
            <small>Verified sources</small>
          </div>

          <div>
            <span>Generated By</span>
            <strong>{deliverable.generatedBy}</strong>
            <small>Execution runtime</small>
          </div>

          <div>
            <span>File Size</span>
            <strong>{deliverable.size}</strong>
            <small>{deliverable.type}</small>
          </div>
        </div>

        <div className="deliverable-details__audit">
          <div className="deliverable-details__audit-icon">
            <ShieldCheck size={16} />
          </div>

          <div>
            <span>AUDIT RELATIONSHIP</span>

            <strong>{deliverable.auditId}</strong>

            <p>
              This deliverable is associated with an audit
              record for traceability.
            </p>
          </div>

          <button
            type="button"
            onClick={handleAudit}
            aria-label="Open audit event"
          >
            <ArrowUpRight size={14} />
          </button>
        </div>
      </aside>
    </>
  );
}